const exactExerciseNames: Record<string, string> = {
  "3/4 sit-up": "Gập bụng 3/4",
  "45° side bend": "Gập người sang bên 45°",
  "air bike": "Đạp xe trên không",
  "all fours squad stretch": "Giãn cơ đùi trước tư thế bò",
  "alternate heel touchers": "Chạm gót chân luân phiên",
  "ankle circles": "Xoay cổ chân",
  "archer pull up": "Kéo xà kiểu cung thủ",
  "archer push up": "Chống đẩy kiểu cung thủ",
  "barbell bench press": "Đẩy ngực ghế ngang với tạ đòn",
  "barbell deadlift": "Deadlift với tạ đòn",
  "barbell full squat": "Squat sâu với tạ đòn",
  "burpee": "Burpee toàn thân",
  "jumping jack": "Bật nhảy dang tay chân",
  "mountain climber": "Leo núi tại chỗ",
  "pull-up": "Kéo xà",
  "push-up": "Chống đẩy",
};

const exercisePhraseRules: Array<[RegExp, string]> = [
  [/\bromanian deadlift\b/gi, "deadlift Romania"],
  [/\bstiff leg deadlift\b/gi, "deadlift chân thẳng"],
  [/\bsumo deadlift\b/gi, "deadlift sumo"],
  [/\bbench front squat\b/gi, "front squat với ghế"],
  [/\bincline bench press\b/gi, "đẩy ngực ghế dốc lên"],
  [/\bdecline bench press\b/gi, "đẩy ngực ghế dốc xuống"],
  [/\bbench press\b/gi, "đẩy ngực ghế ngang"],
  [/\bchest press\b/gi, "đẩy ngực"],
  [/\bshoulder press\b/gi, "đẩy vai"],
  [/\boverhead press\b/gi, "đẩy tạ qua đầu"],
  [/\bmilitary press\b/gi, "đẩy vai quân đội"],
  [/\bleg press\b/gi, "đạp chân"],
  [/\bfront squat\b/gi, "front squat"],
  [/\bback squat\b/gi, "back squat"],
  [/\bsplit squat\b/gi, "split squat"],
  [/\bhack squat\b/gi, "hack squat"],
  [/\bgoblet squat\b/gi, "goblet squat"],
  [/\bfull squat\b/gi, "squat sâu"],
  [/\bdeadlift\b/gi, "deadlift"],
  [/\bpull[ -]?up\b/gi, "kéo xà"],
  [/\bchin[ -]?up\b/gi, "kéo xà tay ngửa"],
  [/\bpush[ -]?up\b/gi, "chống đẩy"],
  [/\blat pulldown\b/gi, "kéo xô"],
  [/\bpulldown\b/gi, "kéo cáp xuống"],
  [/\bbent over row\b/gi, "kéo tạ cúi người"],
  [/\bupright row\b/gi, "kéo tạ thẳng đứng"],
  [/\bseated row\b/gi, "kéo cáp ngồi"],
  [/\bbiceps curl\b/gi, "cuốn tay trước"],
  [/\bhammer curl\b/gi, "cuốn búa"],
  [/\bpreacher curl\b/gi, "cuốn tay trước ghế Scott"],
  [/\bwrist curl\b/gi, "cuốn cổ tay"],
  [/\breverse curl\b/gi, "cuốn tay ngược"],
  [/\btriceps extension\b/gi, "duỗi tay sau"],
  [/\bleg extension\b/gi, "duỗi đùi trước"],
  [/\bback extension\b/gi, "duỗi lưng"],
  [/\bhip extension\b/gi, "duỗi hông"],
  [/\blateral raise\b/gi, "nâng vai ngang"],
  [/\bfront raise\b/gi, "nâng vai trước"],
  [/\bcalf raise\b/gi, "nhón bắp chân"],
  [/\breverse fly\b/gi, "dang vai sau"],
  [/\bchest fly\b/gi, "ép ngực"],
  [/\bpec deck\b/gi, "ép ngực máy"],
  [/\bleg curl\b/gi, "cuốn đùi sau"],
  [/\bhip thrust\b/gi, "đẩy hông"],
  [/\bglute bridge\b/gi, "cầu mông"],
  [/\bside bend\b/gi, "gập người sang bên"],
  [/\bsit[ -]?up\b/gi, "gập bụng"],
  [/\bcrunch\b/gi, "gập bụng ngắn"],
  [/\bplank\b/gi, "plank"],
  [/\blunge\b/gi, "chùng chân"],
  [/\bstretch\b/gi, "giãn cơ"],
  [/\bdip\b/gi, "nhúng người"],
  [/\bkickback\b/gi, "đá ra sau"],
  [/\bbridge\b/gi, "tư thế cầu"],
  [/\brotation\b/gi, "xoay"],
  [/\btwist\b/gi, "vặn người"],
  [/\bhigh knees\b/gi, "nâng cao gối"],
  [/\bjumping jack\b/gi, "bật nhảy dang tay chân"],
  [/\bmountain climber\b/gi, "leo núi tại chỗ"],
  [/\bez barbell\b/gi, "thanh tạ EZ"],
  [/\bbarbell\b/gi, "tạ đòn"],
  [/\bdumbbell\b/gi, "tạ đơn"],
  [/\bkettlebell\b/gi, "tạ ấm"],
  [/\bcable\b/gi, "cáp"],
  [/\bresistance band\b/gi, "dây kháng lực"],
  [/\bband\b/gi, "dây kháng lực"],
  [/\bsmith machine\b/gi, "máy Smith"],
  [/\bleverage machine\b/gi, "máy đòn bẩy"],
  [/\bmachine\b/gi, "máy"],
  [/\bbodyweight\b/gi, "trọng lượng cơ thể"],
  [/\bbody weight\b/gi, "trọng lượng cơ thể"],
  [/\bweighted\b/gi, "có thêm tạ"],
  [/\bassisted\b/gi, "có hỗ trợ"],
  [/\balternate\b/gi, "luân phiên"],
  [/\balternating\b/gi, "luân phiên"],
  [/\bsingle arm\b/gi, "một tay"],
  [/\bone arm\b/gi, "một tay"],
  [/\bsingle leg\b/gi, "một chân"],
  [/\bone leg\b/gi, "một chân"],
  [/\bstanding\b/gi, "đứng"],
  [/\bseated\b/gi, "ngồi"],
  [/\blying\b/gi, "nằm"],
  [/\bincline\b/gi, "dốc lên"],
  [/\bdecline\b/gi, "dốc xuống"],
  [/\bclose grip\b/gi, "tay hẹp"],
  [/\bwide grip\b/gi, "tay rộng"],
  [/\breverse\b/gi, "ngược"],
  [/\bfront\b/gi, "phía trước"],
  [/\bback\b/gi, "phía sau"],
  [/\bside\b/gi, "bên"],
  [/\braise\b/gi, "nâng"],
  [/\bpress\b/gi, "đẩy"],
  [/\brow\b/gi, "kéo"],
  [/\bcurl\b/gi, "cuốn"],
  [/\bextension\b/gi, "duỗi"],
  [/\bflexion\b/gi, "gập"],
  [/\bfly\b/gi, "dang tay"],
  [/\bsquat\b/gi, "squat"],
];

const exerciseTerms: Record<string, string> = {
  abs: "Cơ bụng",
  abductors: "Cơ dạng đùi",
  adductors: "Cơ khép đùi",
  assisted: "Máy hỗ trợ",
  back: "Lưng",
  band: "Dây kháng lực",
  barbell: "Tạ đòn",
  biceps: "Cơ tay trước",
  "body weight": "Trọng lượng cơ thể",
  "bosu ball": "Bóng BOSU",
  cable: "Máy cáp",
  calves: "Bắp chân",
  cardio: "Tim mạch",
  chest: "Ngực",
  core: "Cơ lõi",
  dumbbell: "Tạ đơn",
  "elliptical machine": "Máy elliptical",
  "ez barbell": "Thanh tạ EZ",
  forearms: "Cẳng tay",
  glutes: "Cơ mông",
  hammer: "Búa tập lực",
  hamstrings: "Cơ đùi sau",
  "hip flexors": "Cơ gấp hông",
  kettlebell: "Tạ ấm",
  lats: "Cơ xô",
  "leverage machine": "Máy đòn bẩy",
  "lower arms": "Cẳng tay",
  "lower back": "Lưng dưới",
  "lower legs": "Cẳng chân",
  "medicine ball": "Bóng tạ",
  neck: "Cổ",
  obliques: "Cơ liên sườn",
  "olympic barbell": "Tạ đòn Olympic",
  pectorals: "Cơ ngực",
  quads: "Cơ đùi trước",
  "resistance band": "Dây kháng lực",
  rhomboids: "Cơ trám lưng",
  roller: "Con lăn",
  rope: "Dây thừng",
  shoulders: "Vai",
  "skierg machine": "Máy SkiErg",
  "sled machine": "Xe kéo tạ",
  "smith machine": "Máy Smith",
  "stability ball": "Bóng thăng bằng",
  "stationary bike": "Xe đạp tại chỗ",
  "stepmill machine": "Máy leo cầu thang",
  tire: "Lốp tập",
  "trap bar": "Thanh trap bar",
  traps: "Cơ cầu vai",
  triceps: "Cơ tay sau",
  "upper arms": "Cánh tay",
  "upper body ergometer": "Máy quay tay",
  "upper legs": "Đùi",
  waist: "Eo và bụng",
  weighted: "Có thêm tạ",
  "wheel roller": "Con lăn bụng",
};

function sentenceCase(value: string) {
  const cleaned = value.replace(/\s+/g, " ").trim();

  if (!cleaned) {
    return "";
  }

  return cleaned.charAt(0).toLocaleUpperCase("vi-VN") + cleaned.slice(1);
}

export function translateExerciseName(name: string) {
  const normalizedName = name.trim().toLocaleLowerCase("en-US");
  const exactName = exactExerciseNames[normalizedName];

  if (exactName) {
    return exactName;
  }

  const translatedName = exercisePhraseRules.reduce(
    (currentName, [pattern, replacement]) => currentName.replace(pattern, replacement),
    normalizedName,
  );

  return sentenceCase(translatedName);
}

export function translateExerciseTerm(value: string) {
  const normalizedValue = value.trim().toLocaleLowerCase("en-US");

  return exerciseTerms[normalizedValue] ?? sentenceCase(value);
}
